source 'https://rubygems.org'

gem 'awesome_print'
gem 'rack'
gem 'rack-proxy'
gem 'puma'
gem 'redis'
gem 'rack-test', require: 'rack/test'
gem 'require_all'
gem 'rspec'
gem 'selenium-webdriver'
gem 'rest_client'
gem 'httpclient'
#gem 'logstash-logger'
